---
name: silverblue-nvidia
description: silverblue with nvidia and (minimal) COSMIC
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:    
  - type: dnf
    install:
      packages:
        - distrobox
        - steam-devices
    group-install:
      packages:
        - cosmic-desktop-environment
        - virtualization
    remove:
      packages:
       - firefox
       - nheko
       - thunderbird
       - im-chooser
       - rhythmbox
       - virt-viewer
       - okular
       - libreoffice
       - libreoffice-core
       - libreoffice-data
       - nvtop
       - gnome-system-monitor
       - setroubleshoot
       
  - type: script
    scripts:
      - cachy-nvidia.sh

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - app.zen_browser.zen
          - im.nheko.Nheko
          - org.kde.okular
          - org.libreoffice.LibreOffice
          - it.mijorus.gearlever
          
  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - cosmic-greeter      
        - scx_loader.service
    
  - type: signing
