---
name: silverblue-nvidia
description: silverblue with nvidia and (minimal) COSMIC
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - type: dnf
    install:
      packages:
        - distrobox
        - steam-devices
    group-install:
      packages:
        - cosmic-desktop-environment
        - virtualization
    remove:
      packages:
       - firefox

  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - cosmic-greeter      
        
  - type: signing
