---
name: silverblue-nvidia
description: silverblue with nvidia and (minimal) COSMIC
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - bieszczaders/kernel-cachyos-lto
    install:
      packages:
        - distrobox
        - steam-devices
    group-install:
      packages:
        - cosmic-desktop-environment
        - virtualization
    remove:
      packages:
       - firefox
       - nheko
       - thunderbird
       - im-chooser
       - rhythmbox
       - virt-viewer
       - okular
       - libreoffice
       - libreoffice-core
       - libreoffice-data
       - nvtop
       - gnome-system-monitor
       - setroubleshoot
    
    replace:
    - from-repo: copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-lto
      packages:
        - old: kernel
          new: kernel-cachyos-lto
        - old: kernel-core
          new: kernel-cachyos-lto-core
        - old: kernel-modules
          new: kernel-cachyos-lto-modules
        - old: kernel-modules-extra
          new: kernel-cachyos-lto-modules-extra   
          
  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - app.zen_browser.zen
          - im.nheko.Nheko
          - org.kde.okular
          - org.libreoffice.LibreOffice
          
  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - cosmic-greeter      
    
  - type: signing
