---
name: silverblue-nvidia
description: silverblue with nvidia and (minimal) COSMIC
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - "@cosmic-desktop-environment"

      - "@virtualization"
      - distrobox

      - steam-devices
    remove:
      - firefox

  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - com.system76.CosmicGreeter.service      
        
  - type: signing
