---
name: silverblue-nvidia
description: silverblue with nvidia and (minimal) COSMIC
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - "@cosmic-desktop-environment"

      - distrobox
      - virt-manager
      - libvirt
      - qemu-kvm

      - steam-devices
    remove:
      - firefox

  - type: systemd
    units:
      - libvirtd.service
      - com.system76.CosmicGreeter.service
      
  - type: signing
