---
name: silverblue-nvidia
description: silverblue with nvidia and (minimal) COSMIC
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:    
  - type: dnf
    repos:
      copr:
        - name: trixieua/mutter-patched
    install:
      packages:
        - gnome-shell
        - gnome-software
        - nautilus
        - gdm
    install:
      packages:
        - distrobox
        - steam-devices
    group-install:
      packages:
        - virtualization
        
  - type: script
    scripts:
      - cachy-nvidia.sh

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - app.zen_browser.zen
          - app.devsuite.Ptyxis
          - im.nheko.Nheko
          - org.kde.okular
          - org.libreoffice.LibreOffice
          - it.mijorus.gearlever
          
  - type: script
    snippets:
      - "systemctl set-default graphical.target"
    
  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - scx_loader.service
    
  - type: signing
