---
name: silverblue-nvidia
description: silverblue with nvidia and (minimal) COSMIC
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:
  - type: script
    snippets:
      - "mkdir -p /run/procs; touch /run/procs/1"
      - "mkdir -p /var/tmp"
      
  - type: dnf
    repos:
      copr:
        - bieszczaders/kernel-cachyos-lto
    install:
      packages:
        - distrobox
        - steam-devices
    group-install:
      packages:
        - cosmic-desktop-environment
        - virtualization
    remove:
      packages:
       - firefox
       - nheko
       - thunderbird
       - im-chooser
       - rhythmbox
       - virt-viewer
       - okular
       - libreoffice
       - libreoffice-core
       - libreoffice-data
       - nvtop
       - gnome-system-monitor
       - setroubleshoot
       
  - type: script
    snippets:
      - "dnf install -y --repo=copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-lto kernel-cachyos-lto kernel-cachyos-lto-core kernel-cachyos-lto-modules kernel-cachyos-lto-modules-core"
      - "KVER=$(rpm -q --queryformat='%{VERSION}-%{RELEASE}.%{ARCH}' kernel-cachyos-lto-core | head -n 1)"
      - "depmod -a $KVER"
      - "rpm-ostree override replace --from repo=copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-lto kernel=kernel-cachyos-lto kernel-core=kernel-cachyos-lto-core kernel-modules=kernel-cachyos-lto-modules kernel-modules-core=kernel-cachyos-lto-modules-core kernel-modules-extra=kernel-cachyos-lto-modules"
            
  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - app.zen_browser.zen
          - im.nheko.Nheko
          - org.kde.okular
          - org.libreoffice.LibreOffice
          
  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - cosmic-greeter      
    
  - type: signing
